# Generated by Django 4.2.1 on 2024-10-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
